version: 0.2
# run-as: linux
phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y sshpass zip unzip
  build:
    commands:
      - echo "hello"
      - SSHPASS='Root@123' sshpass -e ssh root@15.206.67.253
      - ssh -T root@15.206.67.253 |sleep 10 |echo "Root@123"
      - chmod -x test.sh
      -  ./test.sh
  post_build:
    commands:
      - echo "hello its running"
