version: 0.2
# run-as: linux
phases:
  pre_build:
    commands:
      - apt-get install sshpass
  build:
    commands:
      - echo "hello"
      - sshpass -p Root@123 ssh root@15.206.67.253
      - chmod -x test.sh
      - ./test.sh
  post_build:
    commands:
      - echo "hello its running"
