version: 0.2
# run-as: linux
os: linux
phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y sshpass zip unzip
  build:
    shell:
    commands:
      - echo "hello"
      - sshpass -p "Root@123" StrictHostKeyChecking=no ssh root@15.206.67.253
      - chmod -x test.sh
      -  ./test.sh
  post_build:
    commands:
      - echo "hello its running"
