version: 0.0
os: linux
phase:
  pre_build:
    command:
      - sudo apt install sshpass
  build:
    command:
      - sshpass -p ${{secret.PASSWD}} ssh root@15.206.67.253
      - chmod -x test.sh
      - ./test.sh

