version: 0.2
env:
  shell: /bin/bash
phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y sshpass zip unzip
  build:
    shell:
    commands:
      - echo "hello"
      - ssh -i $keyfile ec2-user@ec2-15-206-67-253.ap-south-1.compute.amazonaws.com
      - chmod -x test.sh
      -  ./test.sh
  post_build:
    commands:
      - echo "hello its running"
