version: 0.2
env:
  shell: /bin/bash
phases:
  pre_build:
    commands:
      - aws --version
      - aws s3 ls
  build:
    shell:
    commands:
      - echo "hello"
      - sshpass -p 'Root@123' ssh   -o StrictHostKeyChecking=no -T  root@15.206.67.253
      - hostname -i
      - whoami
      - ls
      - chmod -x test.sh
      -  ./test.sh
  post_build:
    commands:
      - echo "hello its running"
