version: 0.2
env:
  shell: /bin/bash
phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y sshpass zip unzip
  build:
    shell:
    commands:
      - echo "hello"
      - sshpass -p 'Root@123' ssh   -o StrictHostKeyChecking=no   root@15.206.67.253
      - ls
      - chmod -x test.sh
      -  ./test.sh
  post_build:
    commands:
      - echo "hello its running"
