version: 0.2
# run-as: linux
phase:
  build:
    command:
      - echo "hello"
      - sshpass -p ${PASSWD} ssh root@15.206.67.253
      - chmod -x test.sh
      - ./test.sh
  post_build:
    command:
      - echo "hello its running"
