version: 0.2
env:
  shell: /bin/bash
phases:
  pre_build:
    commands:
      - aws configure list
      - aws sts get-caller-identity
  build:
    shell:
    commands:
      - echo "hello"
      - aws s3 cp s3://test-viswanth/viswanth.pem .
      - ls
      - chmod -R 777 viswanth.pem
      - ls -l
      - ssh -i viswanth.pem root@15.206.67.253
      - hostname -i
      - whoami
      - ls
      - chmod -x test.sh
      -  ./test.sh
  post_build:
    commands:
      - echo "hello its running"
