version: 0.2
env:
  shell: /bin/bash
phases:
  pre_build:
    commands:
      - aws configure list
      - aws sts get-caller-identity
  build:
    shell:
    commands:
      - echo "hello"
      - aws s3 cp s3://test-viswanth/viswanth.pem .
      - ls
      - chmod -R 400 viswanth.pem
      - ls -l
      - ssh -T -o " StrictHostKeyChecking no"  -i viswanth.pem  ec2-user@172.31.25.234 ./test.sh
  post_build:
    commands:
      - echo "hello its running"
