version: 0.2
# run-as: linux
phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y sshpass zip unzip
  build:
    commands:
      sh "echo hello"
      sh 'sshpass -p Root@123 ssh root@15.206.67.253'
      sh 'chmod -x test.sh,
      sh './test.sh'
  post_build:
    commands:
      - echo "hello its running"
